My Project: Weather_Testing.cpp File Reference
Weather_Testing.cpp File Reference
#include <iostream>
#include "Weather.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 4 of file Weather_Testing.cpp.
{
    Weather myWeather;
    myWeather.SetSolar(3);
    myWeather.SetSpeed(6);
    myWeather.SetTemp(9);
    myWeather.GetSolar();
    myWeather.GetSpeed();
    myWeather.GetTemp();
    cout <<"Weather-Test: (Solar) "<< myWeather.GetSolar() << endl;
    cout <<"Weather-Test: (Speed) "<< myWeather.GetSpeed() << endl;
    cout <<"Weather-Test: (Temperature) "<< myWeather.GetTemp() << endl;
    cout <<"Weather-Test: "<< myWeather.GetSolar() << ',' << myWeather.GetSpeed() << ',' << myWeather.GetTemp() << endl;
    return 0;
}
References Weather::GetSolar(), Weather::GetSpeed(), Weather::GetTemp(), Weather::SetSolar(), Weather::SetSpeed(), and Weather::SetTemp().