My Project: WindLog
WindLog
WindLog Class is created to store the Date Class, Time Class and Weather Class.
#include "WindLog.h"
Public Member Functions
WindLog ()
WindLog (Date date, Time time, Weather weather)
Default Constructor for WindLog.
Date GetDate () const
setter for the Weather that is calling from the Time class
Time GetTime () const
getter for the Date from the Date Class
Weather GetWeather () const
getter for the Time from the Time Class
bool operator< (WindLog &windLog) const
This function will overload the "==" operator and will compare two WindLog Objects.
bool operator<= (WindLog &windLog) const
This function will overload the ">" operator and will compare two WindLog Objects.
bool operator== (WindLog &windLog) const
getter for the Time from the Weather Class
bool operator> (WindLog &windLog) const
This function will overload the "<" operator and will compare two WindLog Objects.
bool operator>= (WindLog &windLog) const
This function will overload the "<=" operator and will compare two WindLog Objects.
void SetDate (Date date)
Parameter Constructor for WindLog.
void SetTime (Time time)
setter for the Date that is calling from the Date class
void SetWeather (Weather weather)
setter for the Time that is calling from the Time class
Private Attributes
Date m_date
This function will overload the ">=" operator and will compare two WindLog Objects.
Time m_time
Weather m_weather
Detailed Description
WindLog Class is created to store the Date Class, Time Class and Weather Class.
Author
Tan Hong Rui Freeman
Version
02
Date
22/11/2022 Freeman Tan, Started
Definition at line 20 of file WindLog.h.
Constructor & Destructor Documentation
WindLog() [1/2]
WindLog ()
Definition at line 3 of file WindLog.cpp.
{
    m_date = Date(0,0,0);
    m_time = Time(0,0);
    m_weather = Weather(0,0,0);
}
References Date::Date(), Time::Time(), Weather::Weather(), m_date, m_time, and m_weather.
WindLog() [2/2]
WindLog (Date date, Time time, Weather weather)
Default Constructor for WindLog.
Parameters
An default constructor that is empty
Definition at line 10 of file WindLog.cpp.
{
    m_date = date;
    m_time = time;
    m_weather = weather;
}
References m_date, m_time, and m_weather.
Member Function Documentation
GetDate()
Date GetDate () const
setter for the Weather that is calling from the Time class
Parameters
weather represents private m_weather
Postcondition
weather is changed
Definition at line 33 of file WindLog.cpp.
{
    return m_date;
}
References m_date.
Referenced by operator<(), and operator==().
GetTime()
Time GetTime () const
getter for the Date from the Date Class
Precondition
m_date object must be initialised
Returns
Get Date informations
Definition at line 38 of file WindLog.cpp.
{
    return m_time;
}
References m_time.
Referenced by operator<(), and operator==().
GetWeather()
Weather GetWeather () const
getter for the Time from the Time Class
Precondition
m_time object must be initialised
Returns
Get Time informations
Definition at line 43 of file WindLog.cpp.
{
    return m_weather;
}
References m_weather.
operator<()
bool operator< (WindLog & windLog) const
This function will overload the "==" operator and will compare two WindLog Objects.
Parameters
WindLog& - windLog
Returns
true if two objects have the same value of Time, Date
Definition at line 62 of file WindLog.cpp.
{
    if(GetDate() < windLog.GetDate() || (GetDate() == windLog.GetDate()
        && GetTime() < windLog.GetTime()))
    {
        return true;
    }
    else
    {
        return false;
    }
}
References GetDate(), GetTime(), Date::operator<(), Time::operator<(), and Date::operator==().
Referenced by operator<=(), operator>(), and operator>=().
operator<=()
bool operator<= (WindLog & windLog) const
This function will overload the ">" operator and will compare two WindLog Objects.
Parameters
WindLog& - windLog
Returns
true if two objects have the same value of Time, Date
Definition at line 82 of file WindLog.cpp.
{
    return(*this==windLog || *this < windLog);
}
References operator<(), and operator==().
operator==()
bool operator== (WindLog & windLog) const
getter for the Time from the Weather Class
Precondition
m_weather object must be initialised
Returns
Get Weather informations
Definition at line 49 of file WindLog.cpp.
{
    if(GetDate() == windLog.GetDate() && GetTime() == windLog.GetTime())
    {
        return true;
    }
    else
    {
        return false;
    }
}
References GetDate(), GetTime(), Date::operator==(), and Time::operator==().
Referenced by operator<=(), and operator>().
operator>()
bool operator> (WindLog & windLog) const
This function will overload the "<" operator and will compare two WindLog Objects.
Parameters
WindLog& - windLog
Returns
true if two objects have the same value of Time, Date
Definition at line 76 of file WindLog.cpp.
{
    return!(*this==windLog || *this < windLog);
}
References operator<(), and operator==().
operator>=()
bool operator>= (WindLog & windLog) const
This function will overload the "<=" operator and will compare two WindLog Objects.
Parameters
WindLog& - windLog
Returns
true if two objects have the same value of Time, Date
Definition at line 88 of file WindLog.cpp.
{
    return!(*this<windLog);
}
References operator<().
SetDate()
void SetDate (Date date)
Parameter Constructor for WindLog.
Parameters
An parameter constructor that is use to create or name the objects by variables.
Definition at line 17 of file WindLog.cpp.
{
    m_date = date;
}
References m_date.
SetTime()
void SetTime (Time time)
setter for the Date that is calling from the Date class
Parameters
date represents private m_date
Postcondition
d is changed
Definition at line 22 of file WindLog.cpp.
{
    m_time = time;
}
References m_time.
SetWeather()
void SetWeather (Weather weather)
setter for the Time that is calling from the Time class
Parameters
time represents private m_time
Postcondition
time is changed
Definition at line 27 of file WindLog.cpp.
{
    m_weather = weather;
}
References m_weather.
Member Data Documentation
m_date
Date m_date private
This function will overload the ">=" operator and will compare two WindLog Objects.
Parameters
WindLog& - windLog
Returns
true if two objects have the same value of Time, Date
Definition at line 113 of file WindLog.h.
Referenced by WindLog(), GetDate(), and SetDate().
m_time
Time m_time private
Definition at line 114 of file WindLog.h.
Referenced by WindLog(), GetTime(), and SetTime().
m_weather
Weather m_weather private
Definition at line 115 of file WindLog.h.
Referenced by WindLog(), GetWeather(), and SetWeather().
The documentation for this class was generated from the following files:
WindLog.h
WindLog.cpp