My Project: Time
Time
Time Class is created to store the day, month and year.
#include "Time.h"
Public Member Functions
Time ()
Time (int hours, int minutes)
Default Constructor for Time.
int GetHour () const
setter for the Minute
int GetMinute () const
getter for the Hour
bool operator< (const Time &time) const
This function will overload the operators and compare the two Time Objects.
bool operator<= (const Time &time) const
This function will overload the operators and compare the two Time Objects.
bool operator== (const Time &time) const
getter for the Minute
bool operator> (const Time &time) const
This function will overload the operators and compare the two Time Objects.
bool operator>= (const Time &time) const
This function will overload the operators and compare the two Time Objects.
void SetHour (int hours)
Parameter Constructor for Time.
void SetMinute (int minutes)
setter for the Hour
Private Attributes
int m_hour
This function will overload the operators and compare the two Time Objects.
int m_minute
Detailed Description
Time Class is created to store the day, month and year.
Author
Tan Hong Rui Freeman
Version
02
Date
22/11/2022 Freeman Tan, Started
Definition at line 17 of file Time.h.
Constructor & Destructor Documentation
Time() [1/2]
Time ()
Definition at line 5 of file Time.cpp.
{
    m_hour = 0;
    m_minute = 0;
}
References m_hour, and m_minute.
Time() [2/2]
Time (int hours, int minutes)
Default Constructor for Time.
Parameters
An default constructor that is empty
Definition at line 12 of file Time.cpp.
{
    m_hour = hours;
    m_minute = minutes;
}
References m_hour, and m_minute.
Referenced by WindLog::WindLog().
Member Function Documentation
GetHour()
int GetHour () const
setter for the Minute
Parameters
minutes represents private minute
Postcondition
minute is changed
Definition at line 30 of file Time.cpp.
{
    return m_hour;
}
References m_hour.
Referenced by main(), operator<(), and operator==().
GetMinute()
int GetMinute () const
getter for the Hour
Precondition
hour object must be initialised
Returns
Get the hour
Definition at line 35 of file Time.cpp.
{
    return m_minute;
}
References m_minute.
Referenced by main(), operator<(), and operator==().
operator<()
bool operator< (const Time & time) const
This function will overload the operators and compare the two Time Objects.
Parameters
Time& - time
Returns
true if the two Time objects have the same value of minute, hour
Definition at line 54 of file Time.cpp.
{
    if(GetHour() < time.GetHour() || (GetHour() == time.GetHour()
                                      && GetMinute() < time.GetMinute()))
    {
        return true;
    }
    else
    {
        return false;
    }
}
References GetHour(), and GetMinute().
Referenced by main(), WindLog::operator<(), operator<=(), operator>(), and operator>=().
operator<=()
bool operator<= (const Time & time) const
This function will overload the operators and compare the two Time Objects.
Parameters
Time& - time
Returns
true if this Time come later
Definition at line 74 of file Time.cpp.
{
    return(*this==time || *this < time);
}
References operator<(), and operator==().
Referenced by main().
operator==()
bool operator== (const Time & time) const
getter for the Minute
Precondition
minute object must be initialised
Returns
Get the minute
Definition at line 41 of file Time.cpp.
{
    if(GetMinute() == time.GetMinute() && GetHour() == time.GetHour())
    {
        return true;
    }
    else
    {
        return false;
    }
}
References GetHour(), and GetMinute().
Referenced by main(), operator<=(), WindLog::operator==(), and operator>().
operator>()
bool operator> (const Time & time) const
This function will overload the operators and compare the two Time Objects.
Parameters
Time& - time
Returns
true if this Time come first
Definition at line 68 of file Time.cpp.
{
    return!(*this==time || *this < time);
}
References operator<(), and operator==().
Referenced by main().
operator>=()
bool operator>= (const Time & time) const
This function will overload the operators and compare the two Time Objects.
Parameters
Time& - time
Returns
true if two Time objects have the same value of minute and second or this time will come first
Definition at line 80 of file Time.cpp.
{
    return!(*this < time);
}
References operator<().
Referenced by main().
SetHour()
void SetHour (int hours)
Parameter Constructor for Time.
Parameters
An parameter constructor that is use to create or name the objects by variables.
Definition at line 19 of file Time.cpp.
{
    m_hour = hours;
}
References m_hour.
Referenced by main().
SetMinute()
void SetMinute (int minutes)
setter for the Hour
Parameters
hours represents private hour
Postcondition
hour is changed
Definition at line 24 of file Time.cpp.
{
    m_minute = minutes;
}
References m_minute.
Referenced by main().
Member Data Documentation
m_hour
int m_hour private
This function will overload the operators and compare the two Time Objects.
Parameters
Time& - time
Returns
true if two Time objects have the same value of minute and second or this time will come later
Definition at line 96 of file Time.h.
Referenced by Time(), GetHour(), and SetHour().
m_minute
int m_minute private
Definition at line 97 of file Time.h.
Referenced by Time(), GetMinute(), and SetMinute().
The documentation for this class was generated from the following files:
Time.h
Time.cpp