My Project: Date
Date
Date Class is created to store the day, month and year.
#include "Date.h"
Public Member Functions
Date ()
Date (int day, int month, int year)
Default Constructor for Date.
string ConvertMonth (int month)
getter for the Year
int GetDay () const
setter for the Year
int GetMonth () const
getter for the Day
int GetYear () const
getter for the Month
bool operator< (const Date &date) const
This function will overload the operator and compare the Date objects.
bool operator<= (const Date &date) const
This function will overload the operator and compare the Date objects.
bool operator== (const Date &date) const
function to convert to the integer month into an string month
bool operator> (const Date &date) const
This function will overload the operator and compare the Date objects.
bool operator>= (const Date &date) const
This function will overload the operator and compare the Date objects.
void SetDay (int day)
Parameter Constructor for Date.
void SetMonth (int month)
setter for the Day
void SetYear (int year)
setter for the Month
Private Attributes
int m_day
This function will overload the operator and compare the Date objects.
int m_month
int m_year
Detailed Description
Date Class is created to store the day, month and year.
Author
Tan Hong Rui Freeman
Version
02
Date
22/11/2022 Freeman Tan, Started
Definition at line 18 of file Date.h.
Constructor & Destructor Documentation
Date() [1/2]
Date ()
Definition at line 3 of file Date.cpp.
{
    m_day = 0;
    m_month = 0;
    m_year = 0;
}
References m_day, m_month, and m_year.
Date() [2/2]
Date (int day, int month, int year)
Default Constructor for Date.
Parameters
An default constructor that is empty
Definition at line 10 of file Date.cpp.
{
    m_day = day;
    m_month = month;
    m_year = year;
}
References m_day, m_month, and m_year.
Referenced by WindLog::WindLog().
Member Function Documentation
ConvertMonth()
string ConvertMonth (int month)
getter for the Year
Precondition
m_year object must be initialised
Returns
the Year
Definition at line 49 of file Date.cpp.
{
    switch(month)
    {
    case 1 :
        return "January";
    case 2 :
        return "February";
    case 3 :
        return "March";
    case 4 :
        return "April";
    case 5 :
        return "May";
    case 6 :
        return "June";
    case 7 :
        return "July";
    case 8 :
        return "August";
    case 9 :
        return "September";
    case 10 :
        return "October";
    case 11 :
        return "November";
    case 12 :
        return "December";
    }
}
GetDay()
int GetDay () const
setter for the Year
Parameters
year represents private m_year
Postcondition
year is changed
Definition at line 34 of file Date.cpp.
{
    return m_day;
}
References m_day.
Referenced by main(), operator<(), and operator==().
GetMonth()
int GetMonth () const
getter for the Day
Precondition
m_day object must be initialised
Returns
the Day
Definition at line 39 of file Date.cpp.
{
    return m_month;
}
References m_month.
Referenced by main(), operator<(), and operator==().
GetYear()
int GetYear () const
getter for the Month
Precondition
m_month object must be initialised
Returns
the Month
Definition at line 44 of file Date.cpp.
{
    return m_year;
}
References m_year.
Referenced by main(), operator<(), and operator==().
operator<()
bool operator< (const Date & date) const
This function will overload the operator and compare the Date objects.
Parameters
Date& - date
Returns
true if two objects have the same value of day, month, year
Definition at line 94 of file Date.cpp.
{
    if ((m_year < date.GetYear()) ||
            (m_year < date.GetYear() && m_month < date.GetMonth()) ||
            (m_year < date.GetYear() && m_month < date.GetMonth() && m_day < date.GetDay()))
    {
        return true;
    }
    else
    {
        return false;
    }
}
References GetDay(), GetMonth(), GetYear(), m_day, m_month, and m_year.
Referenced by main(), WindLog::operator<(), operator<=(), operator>(), and operator>=().
operator<=()
bool operator<= (const Date & date) const
This function will overload the operator and compare the Date objects.
Parameters
Date& - date
Returns
true if this day will come later
Definition at line 115 of file Date.cpp.
{
    return(*this == date || *this < date);
}
References operator<(), and operator==().
Referenced by main().
operator==()
bool operator== (const Date & date) const
function to convert to the integer month into an string month
Parameters
month must be initialized
Returns
string month
Definition at line 81 of file Date.cpp.
{
    if(m_year == date.GetYear() && m_month == date.GetMonth() && m_day == date.GetDay())
    {
        return true;
    }
    else
    {
        return false;
    }
}
References GetDay(), GetMonth(), GetYear(), m_day, m_month, and m_year.
Referenced by main(), WindLog::operator<(), operator<=(), WindLog::operator==(), and operator>().
operator>()
bool operator> (const Date & date) const
This function will overload the operator and compare the Date objects.
Parameters
Date& - date
Returns
true if this day will come first
Definition at line 109 of file Date.cpp.
{
    return!(*this == date || *this < date);
}
References operator<(), and operator==().
Referenced by main().
operator>=()
bool operator>= (const Date & date) const
This function will overload the operator and compare the Date objects.
Parameters
Date& - date
Returns
true if two date objects have the same value of day, month, year or this day come first.
Definition at line 121 of file Date.cpp.
{
    return!(*this < date);
}
References operator<().
Referenced by main().
SetDay()
void SetDay (int day)
Parameter Constructor for Date.
Parameters
An parameter constructor that is use to create or name the objects by variables.
Definition at line 18 of file Date.cpp.
{
    m_day = day;
}
References m_day.
Referenced by main().
SetMonth()
void SetMonth (int month)
setter for the Day
Parameters
day represents private m_day
Postcondition
day is changed
Definition at line 23 of file Date.cpp.
{
    m_month = month;
}
References m_month.
Referenced by main().
SetYear()
void SetYear (int year)
setter for the Month
Parameters
month represents private m_month
Postcondition
month is changed
Definition at line 28 of file Date.cpp.
{
    m_year = year;
}
References m_year.
Referenced by main().
Member Data Documentation
m_day
int m_day private
This function will overload the operator and compare the Date objects.
Parameters
Date& - date
Returns
true if two objects have same value of day, month, year or this day come later
Definition at line 121 of file Date.h.
Referenced by Date(), GetDay(), operator<(), operator==(), and SetDay().
m_month
int m_month private
Definition at line 122 of file Date.h.
Referenced by Date(), GetMonth(), operator<(), operator==(), and SetMonth().
m_year
int m_year private
Definition at line 123 of file Date.h.
Referenced by Date(), GetYear(), operator<(), operator==(), and SetYear().
The documentation for this class was generated from the following files:
Date.h
Date.cpp