My Project: Weather
Weather
Weather Class is created to store the Speed, Solar and Temperature.
#include "Weather.h"
Public Member Functions
Weather ()
Weather (float speeds, float solarRadiation, float temperature)
Default Constructor for Weather An default constructor that is empty.
float GetSolar () const
getter for the Speed
float GetSpeed () const
setter for the Temperature
float GetTemp () const
getter for the Solar
void SetSolar (float solarRadiation)
setter for the Speed
void SetSpeed (float speeds)
Parameter Constructor for Weather An parameter constructor that is use to create or name the objects by variables.
void SetTemp (float temperature)
setter for the Solar
Private Attributes
float m_solarRadiation
float m_speed
getter for the Temperature
float m_temperature
Detailed Description
Weather Class is created to store the Speed, Solar and Temperature.
Author
Tan Hong Rui Freeman
Version
02
Date
22/11/2022 Freeman Tan, Started
Definition at line 16 of file Weather.h.
Constructor & Destructor Documentation
Weather() [1/2]
Weather ()
Definition at line 4 of file Weather.cpp.
{
    m_speed = 0;
    m_solarRadiation = 0;
    m_temperature = 0;
}
References m_solarRadiation, m_speed, and m_temperature.
Weather() [2/2]
Weather (float speeds, float solarRadiation, float temperature)
Default Constructor for Weather An default constructor that is empty.
Definition at line 12 of file Weather.cpp.
{
    m_speed = speeds;
    m_solarRadiation = solarRadiation;
    m_temperature = temperature;
}
References m_solarRadiation, m_speed, and m_temperature.
Referenced by WindLog::WindLog().
Member Function Documentation
GetSolar()
float GetSolar () const
getter for the Speed
Precondition
speeds object must be initialized
Returns
float of the speeds
Definition at line 41 of file Weather.cpp.
{
    return m_solarRadiation;
}
References m_solarRadiation.
Referenced by main().
GetSpeed()
float GetSpeed () const
setter for the Temperature
Postcondition
temperature is changed
Parameters
temperature will be changed
Returns
void
Definition at line 36 of file Weather.cpp.
{
    return m_speed;
}
References m_speed.
Referenced by main().
GetTemp()
float GetTemp () const
getter for the Solar
Precondition
solarRadiation object must be initialized
Returns
float of the solars
Definition at line 46 of file Weather.cpp.
{
    return m_temperature;
}
References m_temperature.
Referenced by main().
SetSolar()
void SetSolar (float solarRadiation)
setter for the Speed
Postcondition
speeds is changed
Parameters
speeds will be changed
Returns
void
Definition at line 25 of file Weather.cpp.
{
    m_solarRadiation = solarRadiation;
}
References m_solarRadiation.
Referenced by main().
SetSpeed()
void SetSpeed (float speeds)
Parameter Constructor for Weather An parameter constructor that is use to create or name the objects by variables.
Definition at line 20 of file Weather.cpp.
{
    m_speed = speeds;
}
References m_speed.
Referenced by main().
SetTemp()
void SetTemp (float temperature)
setter for the Solar
Postcondition
solarRadiation is changed
Parameters
solar will be changed
Returns
void
Definition at line 30 of file Weather.cpp.
{
    m_temperature = temperature;
}
References m_temperature.
Referenced by main().
Member Data Documentation
m_solarRadiation
float m_solarRadiation private
Definition at line 80 of file Weather.h.
Referenced by Weather(), GetSolar(), and SetSolar().
m_speed
float m_speed private
getter for the Temperature
Precondition
temperature object must be initialized
Returns
float of the temperature
Definition at line 79 of file Weather.h.
Referenced by Weather(), GetSpeed(), and SetSpeed().
m_temperature
float m_temperature private
Definition at line 81 of file Weather.h.
Referenced by Weather(), GetTemp(), and SetTemp().
The documentation for this class was generated from the following files:
Weather.h
Weather.cpp